name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "1,3,4,7 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Auto build
        run: |
          pnpm build
